[package]
name = "servo"
version = "0.1.0"
authors = ["Karis Sponsler <karis.sponsler@gmail.com>",
           "Ollie Murauskas <alm9@pdx.edu>"]

[[bin]]
name = "server"
path = "src/server.rs"

[dependencies]
